# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{witness}
  s.version = "2.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Hoeksema"]
  s.date = %q{2010-12-13}
  s.description = %q{Witness}
  s.email = %q{steve@seven.net.nz}
  s.extra_rdoc_files = [
    "TODO"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/witness.rb",
    "lib/witness/base.rb",
    "lib/witness/error.rb",
    "spec/spec_helper.rb",
    "spec/support/sample_base.rb",
    "spec/support/sample_verification_request.rb",
    "spec/support/sample_verification_response.rb",
    "spec/witness/base_spec.rb",
    "spec/witness/sample_verification_request_spec.rb",
    "spec/witness/sample_verification_response_spec.rb",
    "spec/witness_spec.rb",
    "witness.gemspec"
  ]
  s.homepage = %q{http://github.com/steveh/witness}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Witness}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/support/sample_base.rb",
    "spec/support/sample_verification_request.rb",
    "spec/support/sample_verification_response.rb",
    "spec/witness/base_spec.rb",
    "spec/witness/sample_verification_request_spec.rb",
    "spec/witness/sample_verification_response_spec.rb",
    "spec/witness_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<sigil>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.1.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_dependency(%q<sigil>, [">= 1.0.0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.1.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    s.add_dependency(%q<sigil>, [">= 1.0.0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.1.0"])
  end
end

